name: Base/initial commit

###
# This workflow is intended to run on repo cloning/templating
# Baseline the service version in pom.xml and push to ECR
###

on:
  push:
    branches:
      - develop
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    name: Build project with Java ${{ matrix.java }}
    timeout-minutes: 30
    env:
      DEVOPS_CICD_ECR_BASE_URL: ${{ secrets.DEVOPS_CICD_ECR_BASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BB_USERNAME: ${{ secrets.BB_USERNAME }}
      BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
      BB_GITHUB_PACKAGES_USER: botuser
      BB_GITHUB_PACKAGES_PAT: ${{ secrets.BB_GITHUB_PACKAGES_PAT}}


    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Maven Setup settings.xml with BB credentials
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/artifactory/repo" }, { "id": "github", "url": "https://maven.pkg.github.com/${GITHUB_REPOSITORY_OWNER}/common" }]'
          plugin_repositories: '[{ "id": "Backbase Repository", "url": "https://repo.backbase.com/artifactory/repo" }]'
          servers: '[{ "id": "Backbase Repository", "username": "${BB_USERNAME}", "password": "${BB_PASSWORD}" }, { "id": "github", "username": "${BB_GITHUB_PACKAGES_USER}", "password": "${BB_GITHUB_PACKAGES_PAT}" }]'

      - name: Set git username and email
        run: |
          git config --global user.email "bot@backbase.com"
          git config --global user.name "Github Actions BOT"
      - name: Generate sources and install dependencies
        run: mvn -e clean install

      - name: Publish to GitHub Packages
        run: mvn deploy -Drevision=${{ github.run_number }} -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY_OWNER}/common




